# Generated by Django 3.2.9 on 2021-12-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_reactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetreaction',
            old_name='reaction',
            new_name='type',
        ),
    ]
