# Generated by Django 3.2.9 on 2021-12-03 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_alter_tweet_user'),
        ('tweet_reactions', '0002_rename_reaction_tweetreaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetreaction',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='tweets.tweet'),
        ),
    ]
