# Generated by Django 3.2.9 on 2021-12-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_reactions', '0003_alter_tweetreaction_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetreaction',
            name='type',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike'), ('Love', 'Love'), ('Sad', 'Sad')], max_length=25),
        ),
    ]
